/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createInventoryStorageUnitFromDiscriminatorValue, serializeCreateInventoryStorageUnitRequest, type CreateInventoryStorageUnitRequest, type HttpValidationProblemDetails, type InventoryStorageUnit } from '../../models/index';
// @ts-ignore
import { InventoryStorageUnitsItemRequestBuilderRequestsMetadata, type InventoryStorageUnitsItemRequestBuilder } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/inventory-storage-units
 */
export interface InventoryStorageUnitsRequestBuilder extends BaseRequestBuilder<InventoryStorageUnitsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.inventoryStorageUnits.item collection
     * @param id Unique identifier of the item
     * @returns {InventoryStorageUnitsItemRequestBuilder}
     */
     byId(id: number) : InventoryStorageUnitsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InventoryStorageUnit[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InventoryStorageUnit[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: CreateInventoryStorageUnitRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateInventoryStorageUnitRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const InventoryStorageUnitsRequestBuilderUriTemplate = "{+baseurl}/api/inventory-storage-units";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const InventoryStorageUnitsRequestBuilderNavigationMetadata: Record<Exclude<keyof InventoryStorageUnitsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: InventoryStorageUnitsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const InventoryStorageUnitsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: InventoryStorageUnitsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createInventoryStorageUnitFromDiscriminatorValue,
    },
    post: {
        uriTemplate: InventoryStorageUnitsRequestBuilderUriTemplate,
        responseBodyContentType: "application/problem+json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateInventoryStorageUnitRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
