/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSentNotificationResponseFromDiscriminatorValue, type SentNotificationResponse } from '../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/notifications/sent
 */
export interface SentRequestBuilder extends BaseRequestBuilder<SentRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SentNotificationResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<SentRequestBuilderGetQueryParameters> | undefined) : Promise<SentNotificationResponse[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SentRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface SentRequestBuilderGetQueryParameters {
    limit?: number;
}
/**
 * Uri template for the request builder.
 */
export const SentRequestBuilderUriTemplate = "{+baseurl}/api/notifications/sent{?Limit*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const SentRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "limit": "Limit",
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SentRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SentRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSentNotificationResponseFromDiscriminatorValue,
        queryParametersMapper: SentRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
