/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createShoppingListFromDiscriminatorValue, serializeSaveAsTemplateRequest, serializeShoppingList, type HttpValidationProblemDetails, type SaveAsTemplateRequest, type ShoppingList } from '../../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/checklists/{id}/save-as-template
 */
export interface SaveAsTemplateRequestBuilder extends BaseRequestBuilder<SaveAsTemplateRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ShoppingList>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: SaveAsTemplateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ShoppingList | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SaveAsTemplateRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SaveAsTemplateRequestBuilderUriTemplate = "{+baseurl}/api/checklists/{id}/save-as-template";
/**
 * Metadata for all the requests in the request builder.
 */
export const SaveAsTemplateRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: SaveAsTemplateRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createShoppingListFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSaveAsTemplateRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
