/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createDuplicateRecommendationGroupFromDiscriminatorValue, type DuplicateRecommendationGroup } from '../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/shopping-list-recommendations/duplicates
 */
export interface DuplicatesRequestBuilder extends BaseRequestBuilder<DuplicatesRequestBuilder> {
    /**
     * Find groups of near-duplicate suggestions that can be merged.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<DuplicateRecommendationGroup[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<DuplicateRecommendationGroup[] | undefined>;
    /**
     * Find groups of near-duplicate suggestions that can be merged.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DuplicatesRequestBuilderUriTemplate = "{+baseurl}/api/shopping-list-recommendations/duplicates";
/**
 * Metadata for all the requests in the request builder.
 */
export const DuplicatesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DuplicatesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createDuplicateRecommendationGroupFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
