/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRebuildSearchIndexResponseFromDiscriminatorValue, type RebuildSearchIndexResponse } from '../../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/search/rebuild-index/household
 */
export interface HouseholdRequestBuilder extends BaseRequestBuilder<HouseholdRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RebuildSearchIndexResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RebuildSearchIndexResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const HouseholdRequestBuilderUriTemplate = "{+baseurl}/api/search/rebuild-index/household";
/**
 * Metadata for all the requests in the request builder.
 */
export const HouseholdRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: HouseholdRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createRebuildSearchIndexResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
