/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { CardPreferencesRequestBuilderRequestsMetadata, type CardPreferencesRequestBuilder } from './cardPreferences/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/home
 */
export interface HomeRequestBuilder extends BaseRequestBuilder<HomeRequestBuilder> {
    /**
     * The cardPreferences property
     */
    get cardPreferences(): CardPreferencesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const HomeRequestBuilderUriTemplate = "{+baseurl}/api/home";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const HomeRequestBuilderNavigationMetadata: Record<Exclude<keyof HomeRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    cardPreferences: {
        requestsMetadata: CardPreferencesRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
