/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/shopping-list-recommendations/shared
 */
export interface SharedRequestBuilder extends BaseRequestBuilder<SharedRequestBuilder> {
    /**
     * Remove all shared (all-list) suggestions. List-specific suggestions are left untouched.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Remove all shared (all-list) suggestions. List-specific suggestions are left untouched.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SharedRequestBuilderUriTemplate = "{+baseurl}/api/shopping-list-recommendations/shared";
/**
 * Metadata for all the requests in the request builder.
 */
export const SharedRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: SharedRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
};
/* tslint:enable */
/* eslint-enable */
