/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFoodPlanEntryFromDiscriminatorValue, createHttpValidationProblemDetailsFromDiscriminatorValue, serializeAddFoodPlanEntryRequest, type AddFoodPlanEntryRequest, type FoodPlanEntry, type HttpValidationProblemDetails } from '../../../models/index';
// @ts-ignore
import { type WithEntryItemRequestBuilder, WithEntryItemRequestBuilderRequestsMetadata } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/food-plan/entries
 */
export interface EntriesRequestBuilder extends BaseRequestBuilder<EntriesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.foodPlan.entries.item collection
     * @param entryId Unique identifier of the item
     * @returns {WithEntryItemRequestBuilder}
     */
     byEntryId(entryId: number) : WithEntryItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FoodPlanEntry[]>}
     */
     get(requestConfiguration?: RequestConfiguration<EntriesRequestBuilderGetQueryParameters> | undefined) : Promise<FoodPlanEntry[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: AddFoodPlanEntryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<EntriesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AddFoodPlanEntryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface EntriesRequestBuilderGetQueryParameters {
    endDate?: Date;
    startDate?: Date;
}
/**
 * Uri template for the request builder.
 */
export const EntriesRequestBuilderUriTemplate = "{+baseurl}/api/food-plan/entries?endDate={endDate}&startDate={startDate}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const EntriesRequestBuilderNavigationMetadata: Record<Exclude<keyof EntriesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byEntryId: {
        requestsMetadata: WithEntryItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["entryId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const EntriesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: EntriesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createFoodPlanEntryFromDiscriminatorValue,
    },
    post: {
        uriTemplate: EntriesRequestBuilderUriTemplate,
        responseBodyContentType: "application/problem+json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAddFoodPlanEntryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
