/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createNotificationResponseFromDiscriminatorValue, createSendNotificationResponseFromDiscriminatorValue, serializeSendNotificationRequest, serializeSendNotificationResponse, type HttpValidationProblemDetails, type NotificationResponse, type SendNotificationRequest, type SendNotificationResponse } from '../../models/index';
// @ts-ignore
import { NotificationsItemRequestBuilderNavigationMetadata, NotificationsItemRequestBuilderRequestsMetadata, type NotificationsItemRequestBuilder } from './item/index';
// @ts-ignore
import { PreferencesRequestBuilderRequestsMetadata, type PreferencesRequestBuilder } from './preferences/index';
// @ts-ignore
import { ReadAllRequestBuilderRequestsMetadata, type ReadAllRequestBuilder } from './readAll/index';
// @ts-ignore
import { type UnreadCountRequestBuilder, UnreadCountRequestBuilderRequestsMetadata } from './unreadCount/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/notifications
 */
export interface NotificationsRequestBuilder extends BaseRequestBuilder<NotificationsRequestBuilder> {
    /**
     * The preferences property
     */
    get preferences(): PreferencesRequestBuilder;
    /**
     * The readAll property
     */
    get readAll(): ReadAllRequestBuilder;
    /**
     * The unreadCount property
     */
    get unreadCount(): UnreadCountRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.notifications.item collection
     * @param id Unique identifier of the item
     * @returns {NotificationsItemRequestBuilder}
     */
     byId(id: number) : NotificationsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<NotificationResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<NotificationsRequestBuilderGetQueryParameters> | undefined) : Promise<NotificationResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SendNotificationResponse>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: SendNotificationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SendNotificationResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<NotificationsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: SendNotificationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface NotificationsRequestBuilderGetQueryParameters {
    limit?: number;
    unreadOnly?: boolean;
}
/**
 * Uri template for the request builder.
 */
export const NotificationsRequestBuilderUriTemplate = "{+baseurl}/api/notifications{?Limit*,UnreadOnly*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const NotificationsRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "limit": "Limit",
    "unreadOnly": "UnreadOnly",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const NotificationsRequestBuilderNavigationMetadata: Record<Exclude<keyof NotificationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: NotificationsItemRequestBuilderRequestsMetadata,
        navigationMetadata: NotificationsItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    preferences: {
        requestsMetadata: PreferencesRequestBuilderRequestsMetadata,
    },
    readAll: {
        requestsMetadata: ReadAllRequestBuilderRequestsMetadata,
    },
    unreadCount: {
        requestsMetadata: UnreadCountRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const NotificationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: NotificationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createNotificationResponseFromDiscriminatorValue,
        queryParametersMapper: NotificationsRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: NotificationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSendNotificationResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeSendNotificationRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
