/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createInventoryBoxFromDiscriminatorValue, serializeCreateInventoryBoxRequest, serializeInventoryBox, type CreateInventoryBoxRequest, type HttpValidationProblemDetails, type InventoryBox } from '../../models/index';
// @ts-ignore
import { InventoryBoxesItemRequestBuilderRequestsMetadata, type InventoryBoxesItemRequestBuilder } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/inventory-boxes
 */
export interface InventoryBoxesRequestBuilder extends BaseRequestBuilder<InventoryBoxesRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.inventoryBoxes.item collection
     * @param id Unique identifier of the item
     * @returns {InventoryBoxesItemRequestBuilder}
     */
     byId(id: number) : InventoryBoxesItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InventoryBox[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InventoryBox[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InventoryBox>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: CreateInventoryBoxRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InventoryBox | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateInventoryBoxRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const InventoryBoxesRequestBuilderUriTemplate = "{+baseurl}/api/inventory-boxes";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const InventoryBoxesRequestBuilderNavigationMetadata: Record<Exclude<keyof InventoryBoxesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: InventoryBoxesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const InventoryBoxesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: InventoryBoxesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createInventoryBoxFromDiscriminatorValue,
    },
    post: {
        uriTemplate: InventoryBoxesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createInventoryBoxFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateInventoryBoxRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
