/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBillAttachmentResponseFromDiscriminatorValue, type BillAttachmentResponse } from '../../../../models/index';
// @ts-ignore
import { type WithAttachmentItemRequestBuilder, WithAttachmentItemRequestBuilderNavigationMetadata, WithAttachmentItemRequestBuilderRequestsMetadata } from './item/index';
// @ts-ignore
import { MultipartBody, serializeMultipartBody, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/bills/{id}/attachments
 */
export interface AttachmentsRequestBuilder extends BaseRequestBuilder<AttachmentsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.bills.item.attachments.item collection
     * @param attachmentId Unique identifier of the item
     * @returns {WithAttachmentItemRequestBuilder}
     */
     byAttachmentId(attachmentId: number) : WithAttachmentItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BillAttachmentResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BillAttachmentResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     post(body: MultipartBody, requestConfiguration?: RequestConfiguration<AttachmentsRequestBuilderPostQueryParameters> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MultipartBody, requestConfiguration?: RequestConfiguration<AttachmentsRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
export interface AttachmentsRequestBuilderPostQueryParameters {
    name?: string;
}
/**
 * Uri template for the request builder.
 */
export const AttachmentsRequestBuilderUriTemplate = "{+baseurl}/api/bills/{id}/attachments{?name*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AttachmentsRequestBuilderNavigationMetadata: Record<Exclude<keyof AttachmentsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byAttachmentId: {
        requestsMetadata: WithAttachmentItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithAttachmentItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["attachmentId"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const AttachmentsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AttachmentsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createBillAttachmentResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: AttachmentsRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "multipart/form-data",
        requestBodySerializer: serializeMultipartBody,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
