/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTopTagResponseFromDiscriminatorValue, type TopTagResponse } from '../../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes/tags/catalog
 */
export interface CatalogRequestBuilder extends BaseRequestBuilder<CatalogRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TopTagResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TopTagResponse[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CatalogRequestBuilderUriTemplate = "{+baseurl}/api/recipes/tags/catalog";
/**
 * Metadata for all the requests in the request builder.
 */
export const CatalogRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CatalogRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createTopTagResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
