/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithShoppingListItemRequestBuilder, WithShoppingListItemRequestBuilderRequestsMetadata } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/shopping-list-recommendations/by-list
 */
export interface ByListRequestBuilder extends BaseRequestBuilder<ByListRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.shoppingListRecommendations.byList.item collection
     * @param shoppingListId Unique identifier of the item
     * @returns {WithShoppingListItemRequestBuilder}
     */
     byShoppingListId(shoppingListId: number) : WithShoppingListItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ByListRequestBuilderUriTemplate = "{+baseurl}/api/shopping-list-recommendations/by-list";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ByListRequestBuilderNavigationMetadata: Record<Exclude<keyof ByListRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byShoppingListId: {
        requestsMetadata: WithShoppingListItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["shoppingListId"],
    },
};
/* tslint:enable */
/* eslint-enable */
