/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createShoppingListRecommendationFromDiscriminatorValue, serializeCreateRecommendationRequest, type CreateRecommendationRequest, type HttpValidationProblemDetails, type ShoppingListRecommendation } from '../../models/index';
// @ts-ignore
import { AllRequestBuilderRequestsMetadata, type AllRequestBuilder } from './all/index';
// @ts-ignore
import { ShoppingListRecommendationsItemRequestBuilderNavigationMetadata, ShoppingListRecommendationsItemRequestBuilderRequestsMetadata, type ShoppingListRecommendationsItemRequestBuilder } from './item/index';
// @ts-ignore
import { PendingRequestBuilderRequestsMetadata, type PendingRequestBuilder } from './pending/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/shopping-list-recommendations
 */
export interface ShoppingListRecommendationsRequestBuilder extends BaseRequestBuilder<ShoppingListRecommendationsRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * The pending property
     */
    get pending(): PendingRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.shoppingListRecommendations.item collection
     * @param id Unique identifier of the item
     * @returns {ShoppingListRecommendationsItemRequestBuilder}
     */
     byId(id: number) : ShoppingListRecommendationsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ShoppingListRecommendation[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ShoppingListRecommendation[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: CreateRecommendationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateRecommendationRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ShoppingListRecommendationsRequestBuilderUriTemplate = "{+baseurl}/api/shopping-list-recommendations";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ShoppingListRecommendationsRequestBuilderNavigationMetadata: Record<Exclude<keyof ShoppingListRecommendationsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: ShoppingListRecommendationsItemRequestBuilderRequestsMetadata,
        navigationMetadata: ShoppingListRecommendationsItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    all: {
        requestsMetadata: AllRequestBuilderRequestsMetadata,
    },
    pending: {
        requestsMetadata: PendingRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const ShoppingListRecommendationsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ShoppingListRecommendationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createShoppingListRecommendationFromDiscriminatorValue,
    },
    post: {
        uriTemplate: ShoppingListRecommendationsRequestBuilderUriTemplate,
        responseBodyContentType: "application/problem+json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateRecommendationRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
