// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Anything.API.IntegrationTests.ApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Something : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The createdOn property</summary>
        public DateTimeOffset? CreatedOn { get; set; }
        /// <summary>The deletedOn property</summary>
        public DateTimeOffset? DeletedOn { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The modifiedOn property</summary>
        public DateTimeOffset? ModifiedOn { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Anything.API.IntegrationTests.ApiClient.Models.Something"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Anything.API.IntegrationTests.ApiClient.Models.Something CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Anything.API.IntegrationTests.ApiClient.Models.Something();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdOn", n => { CreatedOn = n.GetDateTimeOffsetValue(); } },
                { "deletedOn", n => { DeletedOn = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "modifiedOn", n => { ModifiedOn = n.GetDateTimeOffsetValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdOn", CreatedOn);
            writer.WriteDateTimeOffsetValue("deletedOn", DeletedOn);
            writer.WriteIntValue("id", Id);
            writer.WriteDateTimeOffsetValue("modifiedOn", ModifiedOn);
            writer.WriteStringValue("name", Name);
        }
    }
}
#pragma warning restore CS0618
