/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createUnreadNotificationCountResponseFromDiscriminatorValue, type UnreadNotificationCountResponse } from '../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/notifications/unread-count
 */
export interface UnreadCountRequestBuilder extends BaseRequestBuilder<UnreadCountRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<UnreadNotificationCountResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<UnreadNotificationCountResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UnreadCountRequestBuilderUriTemplate = "{+baseurl}/api/notifications/unread-count";
/**
 * Metadata for all the requests in the request builder.
 */
export const UnreadCountRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: UnreadCountRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createUnreadNotificationCountResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
