/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createInventoryItemFieldResponseFromDiscriminatorValue, serializeInventoryItemFieldResponse, serializeUpdateInventoryItemFieldsRequest, type HttpValidationProblemDetails, type InventoryItemFieldResponse, type UpdateInventoryItemFieldsRequest } from '../../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/inventory-items/{id}/fields
 */
export interface FieldsRequestBuilder extends BaseRequestBuilder<FieldsRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<InventoryItemFieldResponse[]>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     put(body: UpdateInventoryItemFieldsRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<InventoryItemFieldResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateInventoryItemFieldsRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const FieldsRequestBuilderUriTemplate = "{+baseurl}/api/inventory-items/{id}/fields";
/**
 * Metadata for all the requests in the request builder.
 */
export const FieldsRequestBuilderRequestsMetadata: RequestsMetadata = {
    put: {
        uriTemplate: FieldsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createInventoryItemFieldResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateInventoryItemFieldsRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
