/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createMeasurementUnitFromDiscriminatorValue, serializeCreateUnitRequest, serializeMeasurementUnit, type CreateUnitRequest, type HttpValidationProblemDetails, type MeasurementUnit } from '../../models/index';
// @ts-ignore
import { ExportRequestBuilderRequestsMetadata, type ExportRequestBuilder } from './exportEscaped/index';
// @ts-ignore
import { ImportRequestBuilderRequestsMetadata, type ImportRequestBuilder } from './importEscaped/index';
// @ts-ignore
import { type UnitsItemRequestBuilder, UnitsItemRequestBuilderRequestsMetadata } from './item/index';
// @ts-ignore
import { SeedDefaultsRequestBuilderRequestsMetadata, type SeedDefaultsRequestBuilder } from './seedDefaults/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/units
 */
export interface UnitsRequestBuilder extends BaseRequestBuilder<UnitsRequestBuilder> {
    /**
     * The export property
     */
    get exportEscaped(): ExportRequestBuilder;
    /**
     * The import property
     */
    get importEscaped(): ImportRequestBuilder;
    /**
     * The seedDefaults property
     */
    get seedDefaults(): SeedDefaultsRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.units.item collection
     * @param id Unique identifier of the item
     * @returns {UnitsItemRequestBuilder}
     */
     byId(id: number) : UnitsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MeasurementUnit[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MeasurementUnit[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<MeasurementUnit>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: CreateUnitRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<MeasurementUnit | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateUnitRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UnitsRequestBuilderUriTemplate = "{+baseurl}/api/units";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UnitsRequestBuilderNavigationMetadata: Record<Exclude<keyof UnitsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: UnitsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    exportEscaped: {
        requestsMetadata: ExportRequestBuilderRequestsMetadata,
    },
    importEscaped: {
        requestsMetadata: ImportRequestBuilderRequestsMetadata,
    },
    seedDefaults: {
        requestsMetadata: SeedDefaultsRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const UnitsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: UnitsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createMeasurementUnitFromDiscriminatorValue,
    },
    post: {
        uriTemplate: UnitsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createMeasurementUnitFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateUnitRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
