/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createTransferRecommendationsResponseFromDiscriminatorValue, serializeTransferRecommendationsRequest, serializeTransferRecommendationsResponse, type TransferRecommendationsRequest, type TransferRecommendationsResponse } from '../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/shopping-list-recommendations/transfer
 */
export interface TransferRequestBuilder extends BaseRequestBuilder<TransferRequestBuilder> {
    /**
     * Bulk-move suggestions from one scope to another; duplicates in the destination are dropped.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<TransferRecommendationsResponse>}
     */
     post(body: TransferRecommendationsRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<TransferRecommendationsResponse | undefined>;
    /**
     * Bulk-move suggestions from one scope to another; duplicates in the destination are dropped.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: TransferRecommendationsRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TransferRequestBuilderUriTemplate = "{+baseurl}/api/shopping-list-recommendations/transfer";
/**
 * Metadata for all the requests in the request builder.
 */
export const TransferRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: TransferRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createTransferRecommendationsResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeTransferRecommendationsRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
