/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateInventoryBoxRequest}
 */
// @ts-ignore
export function createCreateInventoryBoxRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateInventoryBoxRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateInventoryItemRequest}
 */
// @ts-ignore
export function createCreateInventoryItemRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateInventoryItemRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateInventoryStorageUnitRequest}
 */
// @ts-ignore
export function createCreateInventoryStorageUnitRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateInventoryStorageUnitRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateInviteRequest}
 */
// @ts-ignore
export function createCreateInviteRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateInviteRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateInviteResponse}
 */
// @ts-ignore
export function createCreateInviteResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateInviteResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {CreateSomethingRequest}
 */
// @ts-ignore
export function createCreateSomethingRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoCreateSomethingRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InventoryBox}
 */
// @ts-ignore
export function createInventoryBoxFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInventoryBox;
}
export interface CreateInventoryBoxRequest extends AdditionalDataHolder, Parsable {
    /**
     * The number property
     */
    number?: number | null;
    /**
     * The storageUnitId property
     */
    storageUnitId?: number | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InventoryItem}
 */
// @ts-ignore
export function createInventoryItemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInventoryItem;
}
export interface CreateInventoryItemRequest extends AdditionalDataHolder, Parsable {
    /**
     * The boxId property
     */
    boxId?: number | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The storageUnitId property
     */
    storageUnitId?: number | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {InventoryStorageUnit}
 */
// @ts-ignore
export function createInventoryStorageUnitFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoInventoryStorageUnit;
}
export interface CreateInventoryStorageUnitRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface CreateInviteRequest extends AdditionalDataHolder, Parsable {
    /**
     * The email property
     */
    email?: string | null;
}
export interface CreateInviteResponse extends AdditionalDataHolder, Parsable {
    /**
     * The inviteUrl property
     */
    inviteUrl?: string | null;
    /**
     * The token property
     */
    token?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginRequest}
 */
// @ts-ignore
export function createLoginRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {LoginResponse}
 */
// @ts-ignore
export function createLoginResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoLoginResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RefreshTokenRequest}
 */
// @ts-ignore
export function createRefreshTokenRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRefreshTokenRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RefreshTokenResponse}
 */
// @ts-ignore
export function createRefreshTokenResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRefreshTokenResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {RegisterRequest}
 */
// @ts-ignore
export function createRegisterRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoRegisterRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {Something}
 */
// @ts-ignore
export function createSomethingFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoSomething;
}
export interface CreateSomethingRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateInventoryBoxRequest}
 */
// @ts-ignore
export function createUpdateInventoryBoxRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateInventoryBoxRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateInventoryItemRequest}
 */
// @ts-ignore
export function createUpdateInventoryItemRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateInventoryItemRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateInventoryStorageUnitRequest}
 */
// @ts-ignore
export function createUpdateInventoryStorageUnitRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateInventoryStorageUnitRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateProfileRequest}
 */
// @ts-ignore
export function createUpdateProfileRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateProfileRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {UpdateSomethingRequest}
 */
// @ts-ignore
export function createUpdateSomethingRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoUpdateSomethingRequest;
}
/**
 * The deserialization information for the current model
 * @param CreateInventoryBoxRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateInventoryBoxRequest(createInventoryBoxRequest: Partial<CreateInventoryBoxRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "number": n => { createInventoryBoxRequest.number = n.getNumberValue(); },
        "storageUnitId": n => { createInventoryBoxRequest.storageUnitId = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateInventoryItemRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateInventoryItemRequest(createInventoryItemRequest: Partial<CreateInventoryItemRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "boxId": n => { createInventoryItemRequest.boxId = n.getNumberValue(); },
        "description": n => { createInventoryItemRequest.description = n.getStringValue(); },
        "name": n => { createInventoryItemRequest.name = n.getStringValue(); },
        "storageUnitId": n => { createInventoryItemRequest.storageUnitId = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateInventoryStorageUnitRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateInventoryStorageUnitRequest(createInventoryStorageUnitRequest: Partial<CreateInventoryStorageUnitRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createInventoryStorageUnitRequest.name = n.getStringValue(); },
        "type": n => { createInventoryStorageUnitRequest.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateInviteRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateInviteRequest(createInviteRequest: Partial<CreateInviteRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { createInviteRequest.email = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateInviteResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateInviteResponse(createInviteResponse: Partial<CreateInviteResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "inviteUrl": n => { createInviteResponse.inviteUrl = n.getStringValue(); },
        "token": n => { createInviteResponse.token = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param CreateSomethingRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoCreateSomethingRequest(createSomethingRequest: Partial<CreateSomethingRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { createSomethingRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param InventoryBox The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInventoryBox(inventoryBox: Partial<InventoryBox> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdOn": n => { inventoryBox.createdOn = n.getDateValue(); },
        "deletedOn": n => { inventoryBox.deletedOn = n.getDateValue(); },
        "id": n => { inventoryBox.id = n.getNumberValue(); },
        "modifiedOn": n => { inventoryBox.modifiedOn = n.getDateValue(); },
        "number": n => { inventoryBox.number = n.getNumberValue(); },
        "storageUnitId": n => { inventoryBox.storageUnitId = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param InventoryItem The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInventoryItem(inventoryItem: Partial<InventoryItem> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "boxId": n => { inventoryItem.boxId = n.getNumberValue(); },
        "createdOn": n => { inventoryItem.createdOn = n.getDateValue(); },
        "deletedOn": n => { inventoryItem.deletedOn = n.getDateValue(); },
        "description": n => { inventoryItem.description = n.getStringValue(); },
        "id": n => { inventoryItem.id = n.getNumberValue(); },
        "modifiedOn": n => { inventoryItem.modifiedOn = n.getDateValue(); },
        "name": n => { inventoryItem.name = n.getStringValue(); },
        "storageUnitId": n => { inventoryItem.storageUnitId = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param InventoryStorageUnit The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoInventoryStorageUnit(inventoryStorageUnit: Partial<InventoryStorageUnit> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdOn": n => { inventoryStorageUnit.createdOn = n.getDateValue(); },
        "deletedOn": n => { inventoryStorageUnit.deletedOn = n.getDateValue(); },
        "id": n => { inventoryStorageUnit.id = n.getNumberValue(); },
        "modifiedOn": n => { inventoryStorageUnit.modifiedOn = n.getDateValue(); },
        "name": n => { inventoryStorageUnit.name = n.getStringValue(); },
        "type": n => { inventoryStorageUnit.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginRequest(loginRequest: Partial<LoginRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { loginRequest.email = n.getStringValue(); },
        "password": n => { loginRequest.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param LoginResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoLoginResponse(loginResponse: Partial<LoginResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "accessToken": n => { loginResponse.accessToken = n.getStringValue(); },
        "email": n => { loginResponse.email = n.getStringValue(); },
        "name": n => { loginResponse.name = n.getStringValue(); },
        "refreshToken": n => { loginResponse.refreshToken = n.getStringValue(); },
        "role": n => { loginResponse.role = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RefreshTokenRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRefreshTokenRequest(refreshTokenRequest: Partial<RefreshTokenRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "refreshToken": n => { refreshTokenRequest.refreshToken = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RefreshTokenResponse The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRefreshTokenResponse(refreshTokenResponse: Partial<RefreshTokenResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "accessToken": n => { refreshTokenResponse.accessToken = n.getStringValue(); },
        "refreshToken": n => { refreshTokenResponse.refreshToken = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param RegisterRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoRegisterRequest(registerRequest: Partial<RegisterRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "email": n => { registerRequest.email = n.getStringValue(); },
        "inviteToken": n => { registerRequest.inviteToken = n.getStringValue(); },
        "name": n => { registerRequest.name = n.getStringValue(); },
        "password": n => { registerRequest.password = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param Something The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoSomething(something: Partial<Something> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "createdOn": n => { something.createdOn = n.getDateValue(); },
        "deletedOn": n => { something.deletedOn = n.getDateValue(); },
        "id": n => { something.id = n.getNumberValue(); },
        "modifiedOn": n => { something.modifiedOn = n.getDateValue(); },
        "name": n => { something.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateInventoryBoxRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateInventoryBoxRequest(updateInventoryBoxRequest: Partial<UpdateInventoryBoxRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "number": n => { updateInventoryBoxRequest.number = n.getNumberValue(); },
        "storageUnitId": n => { updateInventoryBoxRequest.storageUnitId = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateInventoryItemRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateInventoryItemRequest(updateInventoryItemRequest: Partial<UpdateInventoryItemRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "boxId": n => { updateInventoryItemRequest.boxId = n.getNumberValue(); },
        "description": n => { updateInventoryItemRequest.description = n.getStringValue(); },
        "name": n => { updateInventoryItemRequest.name = n.getStringValue(); },
        "storageUnitId": n => { updateInventoryItemRequest.storageUnitId = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateInventoryStorageUnitRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateInventoryStorageUnitRequest(updateInventoryStorageUnitRequest: Partial<UpdateInventoryStorageUnitRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { updateInventoryStorageUnitRequest.name = n.getStringValue(); },
        "type": n => { updateInventoryStorageUnitRequest.type = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateProfileRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateProfileRequest(updateProfileRequest: Partial<UpdateProfileRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { updateProfileRequest.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @param UpdateSomethingRequest The instance to deserialize into.
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoUpdateSomethingRequest(updateSomethingRequest: Partial<UpdateSomethingRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { updateSomethingRequest.name = n.getStringValue(); },
    }
}
export interface InventoryBox extends AdditionalDataHolder, Parsable {
    /**
     * The createdOn property
     */
    createdOn?: Date | null;
    /**
     * The deletedOn property
     */
    deletedOn?: Date | null;
    /**
     * The id property
     */
    id?: number | null;
    /**
     * The modifiedOn property
     */
    modifiedOn?: Date | null;
    /**
     * The number property
     */
    number?: number | null;
    /**
     * The storageUnitId property
     */
    storageUnitId?: number | null;
}
export interface InventoryItem extends AdditionalDataHolder, Parsable {
    /**
     * The boxId property
     */
    boxId?: number | null;
    /**
     * The createdOn property
     */
    createdOn?: Date | null;
    /**
     * The deletedOn property
     */
    deletedOn?: Date | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: number | null;
    /**
     * The modifiedOn property
     */
    modifiedOn?: Date | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The storageUnitId property
     */
    storageUnitId?: number | null;
}
export interface InventoryStorageUnit extends AdditionalDataHolder, Parsable {
    /**
     * The createdOn property
     */
    createdOn?: Date | null;
    /**
     * The deletedOn property
     */
    deletedOn?: Date | null;
    /**
     * The id property
     */
    id?: number | null;
    /**
     * The modifiedOn property
     */
    modifiedOn?: Date | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface LoginRequest extends AdditionalDataHolder, Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The password property
     */
    password?: string | null;
}
export interface LoginResponse extends AdditionalDataHolder, Parsable {
    /**
     * The accessToken property
     */
    accessToken?: string | null;
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The refreshToken property
     */
    refreshToken?: string | null;
    /**
     * The role property
     */
    role?: string | null;
}
export interface RefreshTokenRequest extends AdditionalDataHolder, Parsable {
    /**
     * The refreshToken property
     */
    refreshToken?: string | null;
}
export interface RefreshTokenResponse extends AdditionalDataHolder, Parsable {
    /**
     * The accessToken property
     */
    accessToken?: string | null;
    /**
     * The refreshToken property
     */
    refreshToken?: string | null;
}
export interface RegisterRequest extends AdditionalDataHolder, Parsable {
    /**
     * The email property
     */
    email?: string | null;
    /**
     * The inviteToken property
     */
    inviteToken?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The password property
     */
    password?: string | null;
}
/**
 * Serializes information the current object
 * @param CreateInventoryBoxRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateInventoryBoxRequest(writer: SerializationWriter, createInventoryBoxRequest: Partial<CreateInventoryBoxRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createInventoryBoxRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("number", createInventoryBoxRequest.number);
    writer.writeNumberValue("storageUnitId", createInventoryBoxRequest.storageUnitId);
    writer.writeAdditionalData(createInventoryBoxRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateInventoryItemRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateInventoryItemRequest(writer: SerializationWriter, createInventoryItemRequest: Partial<CreateInventoryItemRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createInventoryItemRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("boxId", createInventoryItemRequest.boxId);
    writer.writeStringValue("description", createInventoryItemRequest.description);
    writer.writeStringValue("name", createInventoryItemRequest.name);
    writer.writeNumberValue("storageUnitId", createInventoryItemRequest.storageUnitId);
    writer.writeAdditionalData(createInventoryItemRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateInventoryStorageUnitRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateInventoryStorageUnitRequest(writer: SerializationWriter, createInventoryStorageUnitRequest: Partial<CreateInventoryStorageUnitRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createInventoryStorageUnitRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", createInventoryStorageUnitRequest.name);
    writer.writeStringValue("type", createInventoryStorageUnitRequest.type);
    writer.writeAdditionalData(createInventoryStorageUnitRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateInviteRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateInviteRequest(writer: SerializationWriter, createInviteRequest: Partial<CreateInviteRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createInviteRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", createInviteRequest.email);
    writer.writeAdditionalData(createInviteRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateInviteResponse The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateInviteResponse(writer: SerializationWriter, createInviteResponse: Partial<CreateInviteResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createInviteResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("inviteUrl", createInviteResponse.inviteUrl);
    writer.writeStringValue("token", createInviteResponse.token);
    writer.writeAdditionalData(createInviteResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param CreateSomethingRequest The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeCreateSomethingRequest(writer: SerializationWriter, createSomethingRequest: Partial<CreateSomethingRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!createSomethingRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", createSomethingRequest.name);
    writer.writeAdditionalData(createSomethingRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param InventoryBox The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInventoryBox(writer: SerializationWriter, inventoryBox: Partial<InventoryBox> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!inventoryBox || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdOn", inventoryBox.createdOn);
    writer.writeDateValue("deletedOn", inventoryBox.deletedOn);
    writer.writeNumberValue("id", inventoryBox.id);
    writer.writeDateValue("modifiedOn", inventoryBox.modifiedOn);
    writer.writeNumberValue("number", inventoryBox.number);
    writer.writeNumberValue("storageUnitId", inventoryBox.storageUnitId);
    writer.writeAdditionalData(inventoryBox.additionalData);
}
/**
 * Serializes information the current object
 * @param InventoryItem The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInventoryItem(writer: SerializationWriter, inventoryItem: Partial<InventoryItem> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!inventoryItem || isSerializingDerivedType) { return; }
    writer.writeNumberValue("boxId", inventoryItem.boxId);
    writer.writeDateValue("createdOn", inventoryItem.createdOn);
    writer.writeDateValue("deletedOn", inventoryItem.deletedOn);
    writer.writeStringValue("description", inventoryItem.description);
    writer.writeNumberValue("id", inventoryItem.id);
    writer.writeDateValue("modifiedOn", inventoryItem.modifiedOn);
    writer.writeStringValue("name", inventoryItem.name);
    writer.writeNumberValue("storageUnitId", inventoryItem.storageUnitId);
    writer.writeAdditionalData(inventoryItem.additionalData);
}
/**
 * Serializes information the current object
 * @param InventoryStorageUnit The instance to serialize from.
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeInventoryStorageUnit(writer: SerializationWriter, inventoryStorageUnit: Partial<InventoryStorageUnit> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!inventoryStorageUnit || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdOn", inventoryStorageUnit.createdOn);
    writer.writeDateValue("deletedOn", inventoryStorageUnit.deletedOn);
    writer.writeNumberValue("id", inventoryStorageUnit.id);
    writer.writeDateValue("modifiedOn", inventoryStorageUnit.modifiedOn);
    writer.writeStringValue("name", inventoryStorageUnit.name);
    writer.writeStringValue("type", inventoryStorageUnit.type);
    writer.writeAdditionalData(inventoryStorageUnit.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginRequest(writer: SerializationWriter, loginRequest: Partial<LoginRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", loginRequest.email);
    writer.writeStringValue("password", loginRequest.password);
    writer.writeAdditionalData(loginRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param LoginResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeLoginResponse(writer: SerializationWriter, loginResponse: Partial<LoginResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!loginResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("accessToken", loginResponse.accessToken);
    writer.writeStringValue("email", loginResponse.email);
    writer.writeStringValue("name", loginResponse.name);
    writer.writeStringValue("refreshToken", loginResponse.refreshToken);
    writer.writeStringValue("role", loginResponse.role);
    writer.writeAdditionalData(loginResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RefreshTokenRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRefreshTokenRequest(writer: SerializationWriter, refreshTokenRequest: Partial<RefreshTokenRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!refreshTokenRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("refreshToken", refreshTokenRequest.refreshToken);
    writer.writeAdditionalData(refreshTokenRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RefreshTokenResponse The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRefreshTokenResponse(writer: SerializationWriter, refreshTokenResponse: Partial<RefreshTokenResponse> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!refreshTokenResponse || isSerializingDerivedType) { return; }
    writer.writeStringValue("accessToken", refreshTokenResponse.accessToken);
    writer.writeStringValue("refreshToken", refreshTokenResponse.refreshToken);
    writer.writeAdditionalData(refreshTokenResponse.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param RegisterRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeRegisterRequest(writer: SerializationWriter, registerRequest: Partial<RegisterRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!registerRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("email", registerRequest.email);
    writer.writeStringValue("inviteToken", registerRequest.inviteToken);
    writer.writeStringValue("name", registerRequest.name);
    writer.writeStringValue("password", registerRequest.password);
    writer.writeAdditionalData(registerRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param Something The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeSomething(writer: SerializationWriter, something: Partial<Something> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!something || isSerializingDerivedType) { return; }
    writer.writeDateValue("createdOn", something.createdOn);
    writer.writeDateValue("deletedOn", something.deletedOn);
    writer.writeNumberValue("id", something.id);
    writer.writeDateValue("modifiedOn", something.modifiedOn);
    writer.writeStringValue("name", something.name);
    writer.writeAdditionalData(something.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateInventoryBoxRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateInventoryBoxRequest(writer: SerializationWriter, updateInventoryBoxRequest: Partial<UpdateInventoryBoxRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateInventoryBoxRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("number", updateInventoryBoxRequest.number);
    writer.writeNumberValue("storageUnitId", updateInventoryBoxRequest.storageUnitId);
    writer.writeAdditionalData(updateInventoryBoxRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateInventoryItemRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateInventoryItemRequest(writer: SerializationWriter, updateInventoryItemRequest: Partial<UpdateInventoryItemRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateInventoryItemRequest || isSerializingDerivedType) { return; }
    writer.writeNumberValue("boxId", updateInventoryItemRequest.boxId);
    writer.writeStringValue("description", updateInventoryItemRequest.description);
    writer.writeStringValue("name", updateInventoryItemRequest.name);
    writer.writeNumberValue("storageUnitId", updateInventoryItemRequest.storageUnitId);
    writer.writeAdditionalData(updateInventoryItemRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateInventoryStorageUnitRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateInventoryStorageUnitRequest(writer: SerializationWriter, updateInventoryStorageUnitRequest: Partial<UpdateInventoryStorageUnitRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateInventoryStorageUnitRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", updateInventoryStorageUnitRequest.name);
    writer.writeStringValue("type", updateInventoryStorageUnitRequest.type);
    writer.writeAdditionalData(updateInventoryStorageUnitRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateProfileRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateProfileRequest(writer: SerializationWriter, updateProfileRequest: Partial<UpdateProfileRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateProfileRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", updateProfileRequest.name);
    writer.writeAdditionalData(updateProfileRequest.additionalData);
}
/**
 * Serializes information the current object
 * @param isSerializingDerivedType A boolean indicating whether the serialization is for a derived type.
 * @param UpdateSomethingRequest The instance to serialize from.
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeUpdateSomethingRequest(writer: SerializationWriter, updateSomethingRequest: Partial<UpdateSomethingRequest> | undefined | null = {}, isSerializingDerivedType: boolean = false) : void {
    if (!updateSomethingRequest || isSerializingDerivedType) { return; }
    writer.writeStringValue("name", updateSomethingRequest.name);
    writer.writeAdditionalData(updateSomethingRequest.additionalData);
}
export interface Something extends AdditionalDataHolder, Parsable {
    /**
     * The createdOn property
     */
    createdOn?: Date | null;
    /**
     * The deletedOn property
     */
    deletedOn?: Date | null;
    /**
     * The id property
     */
    id?: number | null;
    /**
     * The modifiedOn property
     */
    modifiedOn?: Date | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface UpdateInventoryBoxRequest extends AdditionalDataHolder, Parsable {
    /**
     * The number property
     */
    number?: number | null;
    /**
     * The storageUnitId property
     */
    storageUnitId?: number | null;
}
export interface UpdateInventoryItemRequest extends AdditionalDataHolder, Parsable {
    /**
     * The boxId property
     */
    boxId?: number | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The storageUnitId property
     */
    storageUnitId?: number | null;
}
export interface UpdateInventoryStorageUnitRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
export interface UpdateProfileRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
}
export interface UpdateSomethingRequest extends AdditionalDataHolder, Parsable {
    /**
     * The name property
     */
    name?: string | null;
}
/* tslint:enable */
/* eslint-enable */
