/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, serializeUpdateRecipeRequest, type HttpValidationProblemDetails, type UpdateRecipeRequest } from '../../../models/index';
// @ts-ignore
import { AddToShoppingListRequestBuilderRequestsMetadata, type AddToShoppingListRequestBuilder } from './addToShoppingList/index';
// @ts-ignore
import { ImagesRequestBuilderNavigationMetadata, ImagesRequestBuilderRequestsMetadata, type ImagesRequestBuilder } from './images/index';
// @ts-ignore
import { IngredientsRequestBuilderNavigationMetadata, IngredientsRequestBuilderRequestsMetadata, type IngredientsRequestBuilder } from './ingredients/index';
// @ts-ignore
import { StepsRequestBuilderNavigationMetadata, StepsRequestBuilderRequestsMetadata, type StepsRequestBuilder } from './steps/index';
// @ts-ignore
import { TagsRequestBuilderNavigationMetadata, TagsRequestBuilderRequestsMetadata, type TagsRequestBuilder } from './tags/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes/{id}
 */
export interface RecipesItemRequestBuilder extends BaseRequestBuilder<RecipesItemRequestBuilder> {
    /**
     * The addToShoppingList property
     */
    get addToShoppingList(): AddToShoppingListRequestBuilder;
    /**
     * The images property
     */
    get images(): ImagesRequestBuilder;
    /**
     * The ingredients property
     */
    get ingredients(): IngredientsRequestBuilder;
    /**
     * The steps property
     */
    get steps(): StepsRequestBuilder;
    /**
     * The tags property
     */
    get tags(): TagsRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     put(body: UpdateRecipeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateRecipeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const RecipesItemRequestBuilderUriTemplate = "{+baseurl}/api/recipes/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RecipesItemRequestBuilderNavigationMetadata: Record<Exclude<keyof RecipesItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    addToShoppingList: {
        requestsMetadata: AddToShoppingListRequestBuilderRequestsMetadata,
    },
    images: {
        requestsMetadata: ImagesRequestBuilderRequestsMetadata,
        navigationMetadata: ImagesRequestBuilderNavigationMetadata,
    },
    ingredients: {
        requestsMetadata: IngredientsRequestBuilderRequestsMetadata,
        navigationMetadata: IngredientsRequestBuilderNavigationMetadata,
    },
    steps: {
        requestsMetadata: StepsRequestBuilderRequestsMetadata,
        navigationMetadata: StepsRequestBuilderNavigationMetadata,
    },
    tags: {
        requestsMetadata: TagsRequestBuilderRequestsMetadata,
        navigationMetadata: TagsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const RecipesItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: RecipesItemRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    get: {
        uriTemplate: RecipesItemRequestBuilderUriTemplate,
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    put: {
        uriTemplate: RecipesItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/problem+json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateRecipeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
