/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createSearchResultResponseFromDiscriminatorValue, type SearchResultResponse } from '../../models/index';
// @ts-ignore
import { OverviewRequestBuilderRequestsMetadata, type OverviewRequestBuilder } from './overview/index';
// @ts-ignore
import { RebuildIndexRequestBuilderNavigationMetadata, RebuildIndexRequestBuilderRequestsMetadata, type RebuildIndexRequestBuilder } from './rebuildIndex/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/search
 */
export interface SearchRequestBuilder extends BaseRequestBuilder<SearchRequestBuilder> {
    /**
     * The overview property
     */
    get overview(): OverviewRequestBuilder;
    /**
     * The rebuildIndex property
     */
    get rebuildIndex(): RebuildIndexRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SearchResultResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<SearchRequestBuilderGetQueryParameters> | undefined) : Promise<SearchResultResponse[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<SearchRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface SearchRequestBuilderGetQueryParameters {
    limit?: number;
    term?: string;
}
/**
 * Uri template for the request builder.
 */
export const SearchRequestBuilderUriTemplate = "{+baseurl}/api/search{?Limit*,Term*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const SearchRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "limit": "Limit",
    "term": "Term",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SearchRequestBuilderNavigationMetadata: Record<Exclude<keyof SearchRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    overview: {
        requestsMetadata: OverviewRequestBuilderRequestsMetadata,
    },
    rebuildIndex: {
        requestsMetadata: RebuildIndexRequestBuilderRequestsMetadata,
        navigationMetadata: RebuildIndexRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SearchRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SearchRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSearchResultResponseFromDiscriminatorValue,
        queryParametersMapper: SearchRequestBuilderGetQueryParametersMapper,
    },
};
/* tslint:enable */
/* eslint-enable */
