/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, serializeMergeRecommendationsRequest, type HttpValidationProblemDetails, type MergeRecommendationsRequest } from '../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/shopping-list-recommendations/merge
 */
export interface MergeRequestBuilder extends BaseRequestBuilder<MergeRequestBuilder> {
    /**
     * Merge one or more duplicate suggestions into a single canonical one.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: MergeRecommendationsRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * Merge one or more duplicate suggestions into a single canonical one.
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: MergeRecommendationsRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MergeRequestBuilderUriTemplate = "{+baseurl}/api/shopping-list-recommendations/merge";
/**
 * Metadata for all the requests in the request builder.
 */
export const MergeRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: MergeRequestBuilderUriTemplate,
        responseBodyContentType: "application/problem+json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeMergeRecommendationsRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
