/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createSomethingFromDiscriminatorValue, serializeCreateSomethingRequest, type CreateSomethingRequest, type HttpValidationProblemDetails, type Something } from '../../models/index';
// @ts-ignore
import { SomethingsItemRequestBuilderRequestsMetadata, type SomethingsItemRequestBuilder } from './item/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/somethings
 */
export interface SomethingsRequestBuilder extends BaseRequestBuilder<SomethingsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.api.somethings.item collection
     * @param id Unique identifier of the item
     * @returns {SomethingsItemRequestBuilder}
     */
     byId(id: number) : SomethingsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Something[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Something[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: CreateSomethingRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateSomethingRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SomethingsRequestBuilderUriTemplate = "{+baseurl}/api/somethings";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SomethingsRequestBuilderNavigationMetadata: Record<Exclude<keyof SomethingsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: SomethingsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SomethingsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SomethingsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSomethingFromDiscriminatorValue,
    },
    post: {
        uriTemplate: SomethingsRequestBuilderUriTemplate,
        responseBodyContentType: "application/problem+json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateSomethingRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
