/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEventsTicketResponseFromDiscriminatorValue, type EventsTicketResponse } from '../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/events/ticket
 */
export interface TicketRequestBuilder extends BaseRequestBuilder<TicketRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EventsTicketResponse>}
     */
     post(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EventsTicketResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const TicketRequestBuilderUriTemplate = "{+baseurl}/api/events/ticket";
/**
 * Metadata for all the requests in the request builder.
 */
export const TicketRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: TicketRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createEventsTicketResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
