/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createSuggestionCategoryFromDiscriminatorValue, serializeCreateSuggestionCategoryRequest, serializeSuggestionCategory, type CreateSuggestionCategoryRequest, type HttpValidationProblemDetails, type SuggestionCategory } from '../../models/index';
// @ts-ignore
import { SuggestionCategoriesItemRequestBuilderRequestsMetadata, type SuggestionCategoriesItemRequestBuilder } from './item/index';
// @ts-ignore
import { ReorderRequestBuilderRequestsMetadata, type ReorderRequestBuilder } from './reorder/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/suggestion-categories
 */
export interface SuggestionCategoriesRequestBuilder extends BaseRequestBuilder<SuggestionCategoriesRequestBuilder> {
    /**
     * The reorder property
     */
    get reorder(): ReorderRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.suggestionCategories.item collection
     * @param id Unique identifier of the item
     * @returns {SuggestionCategoriesItemRequestBuilder}
     */
     byId(id: number) : SuggestionCategoriesItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SuggestionCategory[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SuggestionCategory[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SuggestionCategory>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: CreateSuggestionCategoryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SuggestionCategory | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateSuggestionCategoryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const SuggestionCategoriesRequestBuilderUriTemplate = "{+baseurl}/api/suggestion-categories";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SuggestionCategoriesRequestBuilderNavigationMetadata: Record<Exclude<keyof SuggestionCategoriesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: SuggestionCategoriesItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
    reorder: {
        requestsMetadata: ReorderRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const SuggestionCategoriesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: SuggestionCategoriesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createSuggestionCategoryFromDiscriminatorValue,
    },
    post: {
        uriTemplate: SuggestionCategoriesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSuggestionCategoryFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateSuggestionCategoryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
