/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBillAmountEntryResponseFromDiscriminatorValue, createHttpValidationProblemDetailsFromDiscriminatorValue, serializeAddBillAmountEntryRequest, serializeBillAmountEntryResponse, type AddBillAmountEntryRequest, type BillAmountEntryResponse, type HttpValidationProblemDetails } from '../../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/bills/{id}/amount-entries
 */
export interface AmountEntriesRequestBuilder extends BaseRequestBuilder<AmountEntriesRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BillAmountEntryResponse[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BillAmountEntryResponse[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BillAmountEntryResponse>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: AddBillAmountEntryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BillAmountEntryResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: AddBillAmountEntryRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AmountEntriesRequestBuilderUriTemplate = "{+baseurl}/api/bills/{id}/amount-entries";
/**
 * Metadata for all the requests in the request builder.
 */
export const AmountEntriesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AmountEntriesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createBillAmountEntryResponseFromDiscriminatorValue,
    },
    post: {
        uriTemplate: AmountEntriesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createBillAmountEntryResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeAddBillAmountEntryRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
