// <auto-generated/>
#pragma warning disable CS0618
using Anything.API.IntegrationTests.ApiClient.Api.Auth;
using Anything.API.IntegrationTests.ApiClient.Api.Boxes;
using Anything.API.IntegrationTests.ApiClient.Api.Items;
using Anything.API.IntegrationTests.ApiClient.Api.Somethings;
using Anything.API.IntegrationTests.ApiClient.Api.Storageunits;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Anything.API.IntegrationTests.ApiClient.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The auth property</summary>
        public global::Anything.API.IntegrationTests.ApiClient.Api.Auth.AuthRequestBuilder Auth
        {
            get => new global::Anything.API.IntegrationTests.ApiClient.Api.Auth.AuthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The boxes property</summary>
        public global::Anything.API.IntegrationTests.ApiClient.Api.Boxes.BoxesRequestBuilder Boxes
        {
            get => new global::Anything.API.IntegrationTests.ApiClient.Api.Boxes.BoxesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The items property</summary>
        public global::Anything.API.IntegrationTests.ApiClient.Api.Items.ItemsRequestBuilder Items
        {
            get => new global::Anything.API.IntegrationTests.ApiClient.Api.Items.ItemsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The somethings property</summary>
        public global::Anything.API.IntegrationTests.ApiClient.Api.Somethings.SomethingsRequestBuilder Somethings
        {
            get => new global::Anything.API.IntegrationTests.ApiClient.Api.Somethings.SomethingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The storageunits property</summary>
        public global::Anything.API.IntegrationTests.ApiClient.Api.Storageunits.StorageunitsRequestBuilder Storageunits
        {
            get => new global::Anything.API.IntegrationTests.ApiClient.Api.Storageunits.StorageunitsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Anything.API.IntegrationTests.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Anything.API.IntegrationTests.ApiClient.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
