/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createRecipeFromDiscriminatorValue, serializeCreateRecipeRequest, serializeRecipe, type CreateRecipeRequest, type HttpValidationProblemDetails, type Recipe } from '../../models/index';
// @ts-ignore
import { ImportRequestBuilderRequestsMetadata, type ImportRequestBuilder } from './importEscaped/index';
// @ts-ignore
import { RecipesItemRequestBuilderNavigationMetadata, RecipesItemRequestBuilderRequestsMetadata, type RecipesItemRequestBuilder } from './item/index';
// @ts-ignore
import { ParseUrlRequestBuilderRequestsMetadata, type ParseUrlRequestBuilder } from './parseUrl/index';
// @ts-ignore
import { TagsRequestBuilderNavigationMetadata, TagsRequestBuilderRequestsMetadata, type TagsRequestBuilder } from './tags/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes
 */
export interface RecipesRequestBuilder extends BaseRequestBuilder<RecipesRequestBuilder> {
    /**
     * The import property
     */
    get importEscaped(): ImportRequestBuilder;
    /**
     * The parseUrl property
     */
    get parseUrl(): ParseUrlRequestBuilder;
    /**
     * The tags property
     */
    get tags(): TagsRequestBuilder;
    /**
     * Gets an item from the ApiSdk.api.recipes.item collection
     * @param id Unique identifier of the item
     * @returns {RecipesItemRequestBuilder}
     */
     byId(id: number) : RecipesItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Recipe[]>}
     */
     get(requestConfiguration?: RequestConfiguration<RecipesRequestBuilderGetQueryParameters> | undefined) : Promise<Recipe[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<Recipe>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: CreateRecipeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Recipe | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<RecipesRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateRecipeRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
export interface RecipesRequestBuilderGetQueryParameters {
    search?: string;
    tag?: string;
}
/**
 * Uri template for the request builder.
 */
export const RecipesRequestBuilderUriTemplate = "{+baseurl}/api/recipes{?Search*,Tag*}";
/**
 * Mapper for query parameters from symbol name to serialization name represented as a constant.
 */
const RecipesRequestBuilderGetQueryParametersMapper: Record<string, string> = {
    "search": "Search",
    "tag": "Tag",
};
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const RecipesRequestBuilderNavigationMetadata: Record<Exclude<keyof RecipesRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: RecipesItemRequestBuilderRequestsMetadata,
        navigationMetadata: RecipesItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["id"],
    },
    importEscaped: {
        requestsMetadata: ImportRequestBuilderRequestsMetadata,
    },
    parseUrl: {
        requestsMetadata: ParseUrlRequestBuilderRequestsMetadata,
    },
    tags: {
        requestsMetadata: TagsRequestBuilderRequestsMetadata,
        navigationMetadata: TagsRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const RecipesRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: RecipesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createRecipeFromDiscriminatorValue,
        queryParametersMapper: RecipesRequestBuilderGetQueryParametersMapper,
    },
    post: {
        uriTemplate: RecipesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createRecipeFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateRecipeRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
