/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createShoppingListFromDiscriminatorValue, type ShoppingList } from '../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/shopping-lists/completed
 */
export interface CompletedRequestBuilder extends BaseRequestBuilder<CompletedRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ShoppingList[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ShoppingList[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const CompletedRequestBuilderUriTemplate = "{+baseurl}/api/shopping-lists/completed";
/**
 * Metadata for all the requests in the request builder.
 */
export const CompletedRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: CompletedRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createShoppingListFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
