/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AuthRequestBuilderNavigationMetadata, type AuthRequestBuilder } from './auth/index';
// @ts-ignore
import { BillsRequestBuilderNavigationMetadata, BillsRequestBuilderRequestsMetadata, type BillsRequestBuilder } from './bills/index';
// @ts-ignore
import { FoodPlanRequestBuilderNavigationMetadata, type FoodPlanRequestBuilder } from './foodPlan/index';
// @ts-ignore
import { InventoryBoxesRequestBuilderNavigationMetadata, InventoryBoxesRequestBuilderRequestsMetadata, type InventoryBoxesRequestBuilder } from './inventoryBoxes/index';
// @ts-ignore
import { InventoryItemsRequestBuilderNavigationMetadata, InventoryItemsRequestBuilderRequestsMetadata, type InventoryItemsRequestBuilder } from './inventoryItems/index';
// @ts-ignore
import { InventoryStorageUnitsRequestBuilderNavigationMetadata, InventoryStorageUnitsRequestBuilderRequestsMetadata, type InventoryStorageUnitsRequestBuilder } from './inventoryStorageUnits/index';
// @ts-ignore
import { LocationsRequestBuilderNavigationMetadata, LocationsRequestBuilderRequestsMetadata, type LocationsRequestBuilder } from './locations/index';
// @ts-ignore
import { RecipesRequestBuilderNavigationMetadata, RecipesRequestBuilderRequestsMetadata, type RecipesRequestBuilder } from './recipes/index';
// @ts-ignore
import { ShoppingListRecommendationsRequestBuilderNavigationMetadata, ShoppingListRecommendationsRequestBuilderRequestsMetadata, type ShoppingListRecommendationsRequestBuilder } from './shoppingListRecommendations/index';
// @ts-ignore
import { ShoppingListsRequestBuilderNavigationMetadata, ShoppingListsRequestBuilderRequestsMetadata, type ShoppingListsRequestBuilder } from './shoppingLists/index';
// @ts-ignore
import { SomethingsRequestBuilderNavigationMetadata, SomethingsRequestBuilderRequestsMetadata, type SomethingsRequestBuilder } from './somethings/index';
// @ts-ignore
import { type VendorsRequestBuilder, VendorsRequestBuilderNavigationMetadata, VendorsRequestBuilderRequestsMetadata } from './vendors/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The auth property
     */
    get auth(): AuthRequestBuilder;
    /**
     * The bills property
     */
    get bills(): BillsRequestBuilder;
    /**
     * The foodPlan property
     */
    get foodPlan(): FoodPlanRequestBuilder;
    /**
     * The inventoryBoxes property
     */
    get inventoryBoxes(): InventoryBoxesRequestBuilder;
    /**
     * The inventoryItems property
     */
    get inventoryItems(): InventoryItemsRequestBuilder;
    /**
     * The inventoryStorageUnits property
     */
    get inventoryStorageUnits(): InventoryStorageUnitsRequestBuilder;
    /**
     * The locations property
     */
    get locations(): LocationsRequestBuilder;
    /**
     * The recipes property
     */
    get recipes(): RecipesRequestBuilder;
    /**
     * The shoppingListRecommendations property
     */
    get shoppingListRecommendations(): ShoppingListRecommendationsRequestBuilder;
    /**
     * The shoppingLists property
     */
    get shoppingLists(): ShoppingListsRequestBuilder;
    /**
     * The somethings property
     */
    get somethings(): SomethingsRequestBuilder;
    /**
     * The vendors property
     */
    get vendors(): VendorsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    auth: {
        navigationMetadata: AuthRequestBuilderNavigationMetadata,
    },
    bills: {
        requestsMetadata: BillsRequestBuilderRequestsMetadata,
        navigationMetadata: BillsRequestBuilderNavigationMetadata,
    },
    foodPlan: {
        navigationMetadata: FoodPlanRequestBuilderNavigationMetadata,
    },
    inventoryBoxes: {
        requestsMetadata: InventoryBoxesRequestBuilderRequestsMetadata,
        navigationMetadata: InventoryBoxesRequestBuilderNavigationMetadata,
    },
    inventoryItems: {
        requestsMetadata: InventoryItemsRequestBuilderRequestsMetadata,
        navigationMetadata: InventoryItemsRequestBuilderNavigationMetadata,
    },
    inventoryStorageUnits: {
        requestsMetadata: InventoryStorageUnitsRequestBuilderRequestsMetadata,
        navigationMetadata: InventoryStorageUnitsRequestBuilderNavigationMetadata,
    },
    locations: {
        requestsMetadata: LocationsRequestBuilderRequestsMetadata,
        navigationMetadata: LocationsRequestBuilderNavigationMetadata,
    },
    recipes: {
        requestsMetadata: RecipesRequestBuilderRequestsMetadata,
        navigationMetadata: RecipesRequestBuilderNavigationMetadata,
    },
    shoppingListRecommendations: {
        requestsMetadata: ShoppingListRecommendationsRequestBuilderRequestsMetadata,
        navigationMetadata: ShoppingListRecommendationsRequestBuilderNavigationMetadata,
    },
    shoppingLists: {
        requestsMetadata: ShoppingListsRequestBuilderRequestsMetadata,
        navigationMetadata: ShoppingListsRequestBuilderNavigationMetadata,
    },
    somethings: {
        requestsMetadata: SomethingsRequestBuilderRequestsMetadata,
        navigationMetadata: SomethingsRequestBuilderNavigationMetadata,
    },
    vendors: {
        requestsMetadata: VendorsRequestBuilderRequestsMetadata,
        navigationMetadata: VendorsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
