/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AuthRequestBuilderNavigationMetadata, type AuthRequestBuilder } from './auth/index';
// @ts-ignore
import { InventoryBoxesRequestBuilderNavigationMetadata, InventoryBoxesRequestBuilderRequestsMetadata, type InventoryBoxesRequestBuilder } from './inventoryBoxes/index';
// @ts-ignore
import { InventoryItemsRequestBuilderNavigationMetadata, InventoryItemsRequestBuilderRequestsMetadata, type InventoryItemsRequestBuilder } from './inventoryItems/index';
// @ts-ignore
import { InventoryStorageUnitsRequestBuilderNavigationMetadata, InventoryStorageUnitsRequestBuilderRequestsMetadata, type InventoryStorageUnitsRequestBuilder } from './inventoryStorageUnits/index';
// @ts-ignore
import { SomethingsRequestBuilderNavigationMetadata, SomethingsRequestBuilderRequestsMetadata, type SomethingsRequestBuilder } from './somethings/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The auth property
     */
    get auth(): AuthRequestBuilder;
    /**
     * The inventoryBoxes property
     */
    get inventoryBoxes(): InventoryBoxesRequestBuilder;
    /**
     * The inventoryItems property
     */
    get inventoryItems(): InventoryItemsRequestBuilder;
    /**
     * The inventoryStorageUnits property
     */
    get inventoryStorageUnits(): InventoryStorageUnitsRequestBuilder;
    /**
     * The somethings property
     */
    get somethings(): SomethingsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    auth: {
        navigationMetadata: AuthRequestBuilderNavigationMetadata,
    },
    inventoryBoxes: {
        requestsMetadata: InventoryBoxesRequestBuilderRequestsMetadata,
        navigationMetadata: InventoryBoxesRequestBuilderNavigationMetadata,
    },
    inventoryItems: {
        requestsMetadata: InventoryItemsRequestBuilderRequestsMetadata,
        navigationMetadata: InventoryItemsRequestBuilderNavigationMetadata,
    },
    inventoryStorageUnits: {
        requestsMetadata: InventoryStorageUnitsRequestBuilderRequestsMetadata,
        navigationMetadata: InventoryStorageUnitsRequestBuilderNavigationMetadata,
    },
    somethings: {
        requestsMetadata: SomethingsRequestBuilderRequestsMetadata,
        navigationMetadata: SomethingsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
