/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AuthRequestBuilderNavigationMetadata, type AuthRequestBuilder } from './auth/index';
// @ts-ignore
import { BillsRequestBuilderNavigationMetadata, BillsRequestBuilderRequestsMetadata, type BillsRequestBuilder } from './bills/index';
// @ts-ignore
import { ChecklistsRequestBuilderNavigationMetadata, ChecklistsRequestBuilderRequestsMetadata, type ChecklistsRequestBuilder } from './checklists/index';
// @ts-ignore
import { EventsRequestBuilderRequestsMetadata, type EventsRequestBuilder } from './events/index';
// @ts-ignore
import { FoodPlanRequestBuilderNavigationMetadata, type FoodPlanRequestBuilder } from './foodPlan/index';
// @ts-ignore
import { HomeRequestBuilderNavigationMetadata, type HomeRequestBuilder } from './home/index';
// @ts-ignore
import { HouseholdsRequestBuilderNavigationMetadata, HouseholdsRequestBuilderRequestsMetadata, type HouseholdsRequestBuilder } from './households/index';
// @ts-ignore
import { InventoryBoxesRequestBuilderNavigationMetadata, InventoryBoxesRequestBuilderRequestsMetadata, type InventoryBoxesRequestBuilder } from './inventoryBoxes/index';
// @ts-ignore
import { InventoryItemsRequestBuilderNavigationMetadata, InventoryItemsRequestBuilderRequestsMetadata, type InventoryItemsRequestBuilder } from './inventoryItems/index';
// @ts-ignore
import { InventoryStorageUnitsRequestBuilderNavigationMetadata, InventoryStorageUnitsRequestBuilderRequestsMetadata, type InventoryStorageUnitsRequestBuilder } from './inventoryStorageUnits/index';
// @ts-ignore
import { LocationsRequestBuilderNavigationMetadata, LocationsRequestBuilderRequestsMetadata, type LocationsRequestBuilder } from './locations/index';
// @ts-ignore
import { NotesRequestBuilderNavigationMetadata, NotesRequestBuilderRequestsMetadata, type NotesRequestBuilder } from './notes/index';
// @ts-ignore
import { RecipesRequestBuilderNavigationMetadata, RecipesRequestBuilderRequestsMetadata, type RecipesRequestBuilder } from './recipes/index';
// @ts-ignore
import { SearchRequestBuilderNavigationMetadata, SearchRequestBuilderRequestsMetadata, type SearchRequestBuilder } from './search/index';
// @ts-ignore
import { SharedRequestBuilderNavigationMetadata, type SharedRequestBuilder } from './shared/index';
// @ts-ignore
import { ShoppingListRecommendationsRequestBuilderNavigationMetadata, ShoppingListRecommendationsRequestBuilderRequestsMetadata, type ShoppingListRecommendationsRequestBuilder } from './shoppingListRecommendations/index';
// @ts-ignore
import { SomethingsRequestBuilderNavigationMetadata, SomethingsRequestBuilderRequestsMetadata, type SomethingsRequestBuilder } from './somethings/index';
// @ts-ignore
import { SuggestionCategoriesRequestBuilderNavigationMetadata, SuggestionCategoriesRequestBuilderRequestsMetadata, type SuggestionCategoriesRequestBuilder } from './suggestionCategories/index';
// @ts-ignore
import { type UnitsRequestBuilder, UnitsRequestBuilderNavigationMetadata, UnitsRequestBuilderRequestsMetadata } from './units/index';
// @ts-ignore
import { type VendorsRequestBuilder, VendorsRequestBuilderNavigationMetadata, VendorsRequestBuilderRequestsMetadata } from './vendors/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api
 */
export interface ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The auth property
     */
    get auth(): AuthRequestBuilder;
    /**
     * The bills property
     */
    get bills(): BillsRequestBuilder;
    /**
     * The checklists property
     */
    get checklists(): ChecklistsRequestBuilder;
    /**
     * The events property
     */
    get events(): EventsRequestBuilder;
    /**
     * The foodPlan property
     */
    get foodPlan(): FoodPlanRequestBuilder;
    /**
     * The home property
     */
    get home(): HomeRequestBuilder;
    /**
     * The households property
     */
    get households(): HouseholdsRequestBuilder;
    /**
     * The inventoryBoxes property
     */
    get inventoryBoxes(): InventoryBoxesRequestBuilder;
    /**
     * The inventoryItems property
     */
    get inventoryItems(): InventoryItemsRequestBuilder;
    /**
     * The inventoryStorageUnits property
     */
    get inventoryStorageUnits(): InventoryStorageUnitsRequestBuilder;
    /**
     * The locations property
     */
    get locations(): LocationsRequestBuilder;
    /**
     * The notes property
     */
    get notes(): NotesRequestBuilder;
    /**
     * The recipes property
     */
    get recipes(): RecipesRequestBuilder;
    /**
     * The search property
     */
    get search(): SearchRequestBuilder;
    /**
     * The shared property
     */
    get shared(): SharedRequestBuilder;
    /**
     * The shoppingListRecommendations property
     */
    get shoppingListRecommendations(): ShoppingListRecommendationsRequestBuilder;
    /**
     * The somethings property
     */
    get somethings(): SomethingsRequestBuilder;
    /**
     * The suggestionCategories property
     */
    get suggestionCategories(): SuggestionCategoriesRequestBuilder;
    /**
     * The units property
     */
    get units(): UnitsRequestBuilder;
    /**
     * The vendors property
     */
    get vendors(): VendorsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ApiRequestBuilderUriTemplate = "{+baseurl}/api";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApiRequestBuilderNavigationMetadata: Record<Exclude<keyof ApiRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    auth: {
        navigationMetadata: AuthRequestBuilderNavigationMetadata,
    },
    bills: {
        requestsMetadata: BillsRequestBuilderRequestsMetadata,
        navigationMetadata: BillsRequestBuilderNavigationMetadata,
    },
    checklists: {
        requestsMetadata: ChecklistsRequestBuilderRequestsMetadata,
        navigationMetadata: ChecklistsRequestBuilderNavigationMetadata,
    },
    events: {
        requestsMetadata: EventsRequestBuilderRequestsMetadata,
    },
    foodPlan: {
        navigationMetadata: FoodPlanRequestBuilderNavigationMetadata,
    },
    home: {
        navigationMetadata: HomeRequestBuilderNavigationMetadata,
    },
    households: {
        requestsMetadata: HouseholdsRequestBuilderRequestsMetadata,
        navigationMetadata: HouseholdsRequestBuilderNavigationMetadata,
    },
    inventoryBoxes: {
        requestsMetadata: InventoryBoxesRequestBuilderRequestsMetadata,
        navigationMetadata: InventoryBoxesRequestBuilderNavigationMetadata,
    },
    inventoryItems: {
        requestsMetadata: InventoryItemsRequestBuilderRequestsMetadata,
        navigationMetadata: InventoryItemsRequestBuilderNavigationMetadata,
    },
    inventoryStorageUnits: {
        requestsMetadata: InventoryStorageUnitsRequestBuilderRequestsMetadata,
        navigationMetadata: InventoryStorageUnitsRequestBuilderNavigationMetadata,
    },
    locations: {
        requestsMetadata: LocationsRequestBuilderRequestsMetadata,
        navigationMetadata: LocationsRequestBuilderNavigationMetadata,
    },
    notes: {
        requestsMetadata: NotesRequestBuilderRequestsMetadata,
        navigationMetadata: NotesRequestBuilderNavigationMetadata,
    },
    recipes: {
        requestsMetadata: RecipesRequestBuilderRequestsMetadata,
        navigationMetadata: RecipesRequestBuilderNavigationMetadata,
    },
    search: {
        requestsMetadata: SearchRequestBuilderRequestsMetadata,
        navigationMetadata: SearchRequestBuilderNavigationMetadata,
    },
    shared: {
        navigationMetadata: SharedRequestBuilderNavigationMetadata,
    },
    shoppingListRecommendations: {
        requestsMetadata: ShoppingListRecommendationsRequestBuilderRequestsMetadata,
        navigationMetadata: ShoppingListRecommendationsRequestBuilderNavigationMetadata,
    },
    somethings: {
        requestsMetadata: SomethingsRequestBuilderRequestsMetadata,
        navigationMetadata: SomethingsRequestBuilderNavigationMetadata,
    },
    suggestionCategories: {
        requestsMetadata: SuggestionCategoriesRequestBuilderRequestsMetadata,
        navigationMetadata: SuggestionCategoriesRequestBuilderNavigationMetadata,
    },
    units: {
        requestsMetadata: UnitsRequestBuilderRequestsMetadata,
        navigationMetadata: UnitsRequestBuilderNavigationMetadata,
    },
    vendors: {
        requestsMetadata: VendorsRequestBuilderRequestsMetadata,
        navigationMetadata: VendorsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
