/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createRecipeDetailResponseFromDiscriminatorValue, type RecipeDetailResponse } from '../../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes/{id}/details
 */
export interface DetailsRequestBuilder extends BaseRequestBuilder<DetailsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<RecipeDetailResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<RecipeDetailResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const DetailsRequestBuilderUriTemplate = "{+baseurl}/api/recipes/{id}/details";
/**
 * Metadata for all the requests in the request builder.
 */
export const DetailsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: DetailsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createRecipeDetailResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
