/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createHttpValidationProblemDetailsFromDiscriminatorValue, createParsedRecipeResponseFromDiscriminatorValue, serializeParsedRecipeResponse, serializeParseRecipeFromUrlRequest, type HttpValidationProblemDetails, type ParsedRecipeResponse, type ParseRecipeFromUrlRequest } from '../../../models/index';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/recipes/parse-url
 */
export interface ParseUrlRequestBuilder extends BaseRequestBuilder<ParseUrlRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ParsedRecipeResponse>}
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     post(body: ParseRecipeFromUrlRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ParsedRecipeResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ParseRecipeFromUrlRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ParseUrlRequestBuilderUriTemplate = "{+baseurl}/api/recipes/parse-url";
/**
 * Metadata for all the requests in the request builder.
 */
export const ParseUrlRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ParseUrlRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createParsedRecipeResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeParseRecipeFromUrlRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
