/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createBillResponseFromDiscriminatorValue, createHttpValidationProblemDetailsFromDiscriminatorValue, serializeUpdateBillRequest, type BillResponse, type HttpValidationProblemDetails, type UpdateBillRequest } from '../../../models/index';
// @ts-ignore
import { AmountEntriesRequestBuilderRequestsMetadata, type AmountEntriesRequestBuilder } from './amountEntries/index';
// @ts-ignore
import { AttachmentsRequestBuilderNavigationMetadata, AttachmentsRequestBuilderRequestsMetadata, type AttachmentsRequestBuilder } from './attachments/index';
// @ts-ignore
import { PriceHistoryRequestBuilderNavigationMetadata, PriceHistoryRequestBuilderRequestsMetadata, type PriceHistoryRequestBuilder } from './priceHistory/index';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/bills/{id}
 */
export interface BillsItemRequestBuilder extends BaseRequestBuilder<BillsItemRequestBuilder> {
    /**
     * The amountEntries property
     */
    get amountEntries(): AmountEntriesRequestBuilder;
    /**
     * The attachments property
     */
    get attachments(): AttachmentsRequestBuilder;
    /**
     * The priceHistory property
     */
    get priceHistory(): PriceHistoryRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<BillResponse>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<BillResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {HttpValidationProblemDetails} error when the service returns a 400 status code
     */
     put(body: UpdateBillRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: UpdateBillRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BillsItemRequestBuilderUriTemplate = "{+baseurl}/api/bills/{id}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BillsItemRequestBuilderNavigationMetadata: Record<Exclude<keyof BillsItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    amountEntries: {
        requestsMetadata: AmountEntriesRequestBuilderRequestsMetadata,
    },
    attachments: {
        requestsMetadata: AttachmentsRequestBuilderRequestsMetadata,
        navigationMetadata: AttachmentsRequestBuilderNavigationMetadata,
    },
    priceHistory: {
        requestsMetadata: PriceHistoryRequestBuilderRequestsMetadata,
        navigationMetadata: PriceHistoryRequestBuilderNavigationMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const BillsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: BillsItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: BillsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createBillResponseFromDiscriminatorValue,
    },
    put: {
        uriTemplate: BillsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/problem+json",
        errorMappings: {
            400: createHttpValidationProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeUpdateBillRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
