/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createCreateInviteResponseFromDiscriminatorValue, serializeCreateInviteRequest, serializeCreateInviteResponse, type CreateInviteRequest, type CreateInviteResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /api/auth/invites
 */
export interface InvitesRequestBuilder extends BaseRequestBuilder<InvitesRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<CreateInviteResponse>}
     */
     post(body: CreateInviteRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<CreateInviteResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: CreateInviteRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const InvitesRequestBuilderUriTemplate = "{+baseurl}/api/auth/invites";
/**
 * Metadata for all the requests in the request builder.
 */
export const InvitesRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: InvitesRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createCreateInviteResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeCreateInviteRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
